Formatting Mailing Address
mitodl/bootcamp-ecommerce pull request #1022
Opened 2020-09-24 05:20 UTC by HamzaIbnFarooq

#### What are the relevant tickets?
Fixes #1017 

#### What's this PR do?
It formats the mailing address in the footer.

#### How should this be manually tested?
Navigate to any page which shows the footer and mailing address in it.

#### Screenshots
![image](https://user-images.githubusercontent.com/42243411/94103886-14058900-fe4f-11ea-8015-442ad599def0.png)

2020-09-24 13:10 UTC, umarmughal824 approved these changes
LGTM 👍

2020-09-24 13:18 UTC, ahmed-belal commented
@pdpinch could you confirm the UI change?

2020-09-24 17:11 UTC, pdpinch requested changes
Thanks Hamza. 

On the issue there is an acceptance criteria for desktop and mobile screenshots. Can you add a mobile screenshot so we can see what it looks when the browser window is narrow?

This wasn't part of the issue, but why aren't the three columns of text top-aligned? Is that something you can change?

![image](https://user-images.githubusercontent.com/430126/94177324-5cc93c00-fe67-11ea-9f66-34e5136affcb.png)

2020-09-25 07:26 UTC, HamzaIbnFarooq commented
Thanks for the review @pdpinch.

I have added mobile screenshots in the description and also changed the alignment of those 3 columns, kindly have a look to verify if it is what we require.

2020-09-25 14:21 UTC, pdpinch approved these changes

2020-09-25 14:24 UTC, pdpinch approved these changes
Looks good Hamza. 

I don't think we need any more reviews now that @umarmughal824 and I have both reviewed. 

You can merge this. No need to squash, since there is only one commit already. 

If you merge on Monday it should be included in the release candidate Monday afternoon. You'll need to verify the change on the RC server. 
Please

2020-09-25 16:38 UTC, HamzaIbnFarooq commented
> Looks good Hamza.
> 
> I don't think we need any more reviews now that @umarmughal824 and I have both reviewed.
> 
> You can merge this. No need to squash, since there is only one commit already.
> 
> If you merge on Monday it should be included in the release candidate Monday afternoon. You'll need to verify the change on the RC server.
> Please

Thanks for the explanation, Peter.

I am merging it now.

2020-09-25 16:39 UTC, merged