Filter submissions by run instead of bootcamp
mitodl/bootcamp-ecommerce pull request #1063
Opened 2020-10-20 17:16 UTC by mbertrand

#### What are the relevant tickets?
Closes #1061 

#### What's this PR do?
- Changes the submissions view to filter by BootcampRun instead of Bootcamp, and to omit runs that have ended
- Updates frontend code to reflect the above, and displays title + start date for each run facet

#### How should this be manually tested?
- Log in as an admin and go to `/review`.  You should be able to filter by bootcamp run.
- Change a bootcamp run's end date to the past.  Go back to the `/review` page and there should be no submissions displayed for that run.

#### Screenshots (if appropriate)
<img width="1059" alt="Screen Shot 2020-10-20 at 1 15 47 PM" src="https://user-images.githubusercontent.com/187676/96621315-7c247f00-12d6-11eb-96df-3d13cb1d2c72.png">

2020-10-20 17:59 UTC, mbertrand commented
@pdpinch screenshot is attached to the PR description

2020-10-21 16:24 UTC, gsidebo commented
@mbertrand I'm not seeing a run that I expected to see in the facet list. I have 3 users and 3 runs that I created applications for, and set them all to have an uploaded resume and to await review. I see only 2 of those runs in the facet. Might not be the best way of sharing, but here are some Django admin screenshots to show you what the data looks like. Any ideas about why the "Seed Bootcamp 5" run might not be showing up?

![ss 2020-10-21 at 12 19 31 ](https://user-images.githubusercontent.com/14932219/96748859-1ef10200-1398-11eb-8ff9-233bc029a205.png)
![ss 2020-10-21 at 12 23 27 ](https://user-images.githubusercontent.com/14932219/96748970-3def9400-1398-11eb-9946-8155658a33ae.png)
![ss 2020-10-21 at 12 19 13 ](https://user-images.githubusercontent.com/14932219/96749010-4778fc00-1398-11eb-9196-dbd414729770.png)
![ss 2020-10-21 at 12 18 54 ](https://user-images.githubusercontent.com/14932219/96749086-5cee2600-1398-11eb-863c-49897f0cfb2f.png)

2020-10-21 17:12 UTC, mbertrand commented
@gsidebo does that submissions have a submission_status of 'submitted' and not 'pending'?  Does the submission for that run show up on the master branch?  The run end date is well in the future so that shouldn't be excluding it.

2020-10-21 19:50 UTC, gsidebo requested changes
Just a couple minor comments. The issue I raised before was PEBCAK.

2020-10-21 19:50 UTC, gsidebo commented on applications/views_test.py
> +            )
Can you move this data setup to a fixture and wrap the individual elements into a `SimpleNamespace` or `namedtuple`?

2020-10-21 19:50 UTC, gsidebo commented on static/js/components/SubmissionFacets.js
> +      {facetOptionLabels[facetKey](labelKey.map(label => option[label]))}
There's a lot going on in this line. Might be more readable to assign the `labelKey.map` result to a variable

2020-10-21 20:30 UTC, gsidebo approved these changes
Looks great! 👍

2020-10-22 12:48 UTC, merged