Remove tox, use pytest instead
mitodl/bootcamp-ecommerce pull request #1072
Opened 2020-11-03 20:55 UTC by mbertrand

#### What are the relevant tickets?
Closes #937 

#### What's this PR do?
Removes tox in favor of pytest

#### How should this be manually tested?
Tests on travis should pass
Local tests should pass by running `docker-compose run web pytest .`

2020-11-18 19:34 UTC, gsidebo requested changes

2020-11-18 19:34 UTC, gsidebo commented on travis/python_tests.sh
> +function run_test {
This script in xPro echoes the command before running it. Very useful for reading the test output. Can you add that?

https://github.com/mitodl/mitxpro/blob/master/travis/python_tests.sh#L4-L17

2020-11-18 19:34 UTC, gsidebo commented on README.md
> +    docker-compose run --rm web pytest
This is already part of the common web app, so I don't think we need it here

2020-11-23 13:45 UTC, mbertrand commented
This PR is obsolete (#1086), going to close it.

2020-11-23 13:45 UTC, closed without merging