Added logic to fetch bootcamp runs by display title in mgmt commands
mitodl/bootcamp-ecommerce pull request #1089
Opened 2020-11-25 20:52 UTC by gsidebo

#### What are the relevant tickets?
No ticket. Helps usability with commands like #1084

#### What's this PR do?
In management commands that require a bootcamp run, the run parameter can now be passed in as the `display_title` value of a bootcamp run (e.g.: "Seed Differential Equations, Oct 10, 2020 - Jan 8, 2021")

#### How should this be manually tested?
Use a command like `set_application_state` or `migrate_applications` and provide a `display_title` value as the `--run` param. The command should execute without any errors related to fetching the bootcamp run

#### Any background context you want to provide?
I use these management commands quite a bit, and in almost all cases in the app, we represent bootcamp runs using the `display_title` property. Being able to just copy and paste a display title value makes it _much_ easier to use the management commands

2020-12-02 16:04 UTC, mbertrand requested changes
Looks great. just a couple minor things.

2020-12-02 21:52 UTC, gsidebo commented
@mbertrand I incorporated that feedback, then realized I hadn't updated the documentation in other commands, and _then_ realized there were other commands that could benefit from this. Ready for review again

2020-12-02 21:53 UTC, gsidebo commented on klasses/api.py
> +        return BootcampRun.objects.get(bootcamp__title=run_property)
Yeah I think it's reasonable to expect that the users of the command will be able to figure out the cause of the error

2020-12-03 15:41 UTC, mbertrand approved these changes
👍

2020-12-03 16:59 UTC, merged