Certificate Page template Integration
mitodl/bootcamp-ecommerce pull request #1116
Opened 2020-12-24 12:28 UTC by asadiqbal08

#### What are the relevant tickets?
#1109 #1095 

#### What's this PR do?
Designed the bootcamp certificate and integrated the CMS stuff in it.
Please look around the ticket acceptance criteria to verify changes.

#### Screenshots (Web View):

![screencapture-bc-odl-local-8099-cms-pages-14-edit-preview-2020-12-24-17_21_01](https://user-images.githubusercontent.com/7334669/103088542-f6da8500-460c-11eb-9f06-d2cbb1a02f71.png)
![screencapture-bc-odl-local-8099-cms-pages-14-edit-preview-2020-12-24-17_21_57](https://user-images.githubusercontent.com/7334669/103088552-fb9f3900-460c-11eb-842e-a668cadfcc3a.png)
![screencapture-bc-odl-local-8099-cms-pages-14-edit-preview-2020-12-24-17_22_15](https://user-images.githubusercontent.com/7334669/103088557-fe9a2980-460c-11eb-8e9c-318ce46cd59d.png)

#### Screenshot (Mobile View):
![screencapture-bc-odl-local-8099-cms-pages-14-edit-preview-2020-12-24-17_23_41](https://user-images.githubusercontent.com/7334669/103088560-01951a00-460d-11eb-925c-ce3341ccc327.png)

#### Screenshot (Print Version):

<img width="931" alt="Screen Shot 2020-12-24 at 5 24 25 PM" src="https://user-images.githubusercontent.com/7334669/103088618-3012f500-460d-11eb-9329-8099aca78048.png">

2020-12-28 11:24 UTC, HamzaIbnFarooq commented on static/scss/certificates/certificate.scss
> +    color: #333;
We should move Hex values to `_variables.scss`

2020-12-28 12:15 UTC, HamzaIbnFarooq requested changes
I want some understanding regarding the following point:
1) Do we want any header and footer to be shown on certificate page (on platform/not printed)? (As there isn't any right now)
2) As xPro has a boundary of the certificate, do we need to create a boundary here as well?
3) I am unable to print certificate with the black boundary, similar to your screenshot, why is it so?
4) The help button is also getting printed, don't we need to commit it as well?

2020-12-31 10:25 UTC, HamzaIbnFarooq commented on cms/models_test.py
> +    settings.FEATURES["ENABLE_CERTIFICATE_USER_VIEW"] = True
can we use override_settings here?

2020-12-31 10:25 UTC, HamzaIbnFarooq commented on cms/models_test.py
> +    certificate.save()
Please use `certificate.revoke()` instead.

2020-12-31 10:47 UTC, arslanashraf7 commented on cms/models_test.py
> +    certificate.save()
Updated

2020-12-31 10:47 UTC, arslanashraf7 commented on cms/models_test.py
> +    settings.FEATURES["ENABLE_CERTIFICATE_USER_VIEW"] = True
Updated

2020-12-31 10:52 UTC, HamzaIbnFarooq approved these changes
Final Review:
👍

2020-12-31 11:16 UTC, merged