add certificate command tests
mitodl/bootcamp-ecommerce pull request #1118
Opened 2020-12-30 06:09 UTC by HamzaIbnFarooq

#### What are the relevant tickets?
https://github.com/mitodl/bootcamp-ecommerce/issues/1115

#### What's this PR do?
Adds certificate command tests

#### How should this be manually tested?
Simply run the tests with pytest

2020-12-30 13:54 UTC, umarmughal824 requested changes
some minor changes

2020-12-30 13:54 UTC, umarmughal824 commented on klasses/commands_test.py
> +        out = StringIO()
```suggestion
        output = StringIO()
```

2020-12-30 13:54 UTC, umarmughal824 commented on klasses/commands_test.py
> +        out = StringIO()
also, change its associated uses

2020-12-30 13:54 UTC, umarmughal824 commented on klasses/commands_test.py
> +        method_patch = mocker.patch(method, return_value={"updated": True, "msg": ""})
```suggestion
        patched_method = mocker.patch(method, return_value={"updated": True, "msg": ""})
```

2020-12-30 13:54 UTC, umarmughal824 commented on klasses/commands_test.py
> +        method_patch = mocker.patch(method, return_value={"updated": True, "msg": ""})
also, change its associated uses

2020-12-31 05:47 UTC, HamzaIbnFarooq commented on klasses/commands_test.py
> +        method_patch = mocker.patch(method, return_value={"updated": True, "msg": ""})
updated.

2020-12-31 05:47 UTC, HamzaIbnFarooq commented on klasses/commands_test.py
> +        out = StringIO()
updated.

2020-12-31 07:06 UTC, umarmughal824 approved these changes
👍

2020-12-31 07:07 UTC, merged