Wiretransfer: after data is imported, update the application state
mitodl/bootcamp-ecommerce pull request #1148
Opened 2021-01-26 12:10 UTC by umarmughal824

#### What are the relevant tickets?
fixes #1032 

#### What's this PR do?
Wiretransfer: after data is imported, update the application state

#### How should this be manually tested?
Run the `import_wire_transfers` management command for `AWAITING_PAYMENT` application

#### Screenshots (if appropriate)

2021-01-27 15:07 UTC, mbertrand requested changes

2021-01-27 15:07 UTC, mbertrand commented on ecommerce/api.py
> +            )
Might be better to replace the above with 

```python
complete_successful_order(order, send_receipt=????)
``` 

Not sure if we'd want to send a receipt to the user or not, Peter probably knows.
The above function would also run `novoed_tasks.enroll_users_in_novoed_course.delay` if appropriate.

2021-01-28 13:29 UTC, pdpinch commented
> Not sure if we'd want to send a receipt to the user or not, Peter probably knows.
> 
Yes, we want to send a receipt when the wiretransfer is imported — same as if we had completed a Cybersource transaction. 
> The above function would also run novoed_tasks.enroll_users_in_novoed_course.delay if appropriate.
> 
We also want bootcampers to be enrolled in novoed, if appropriate (i.e. if they have completed paying their personal price, and there is a novoed stub set up).

2021-01-28 13:37 UTC, mbertrand approved these changes
👍

2021-01-28 14:58 UTC, mbertrand requested changes

2021-01-28 14:58 UTC, mbertrand commented on ecommerce/api.py
> +        complete_successful_order(order, send_receipt=False)
Based on Peter's comment, can you drop the `send_receipt=False`?

2021-01-28 15:26 UTC, mbertrand approved these changes
👍

2021-01-28 20:47 UTC, merged