Ab/update refund receipt
mitodl/bootcamp-ecommerce pull request #994
Opened 2020-09-02 16:25 UTC by abeglova

#### What are the relevant tickets?
https://github.com/mitodl/bootcamp-ecommerce/issues/967

#### What's this PR do?
This PR updates the statement to be a bit clearer for refunds

#### How should this be manually tested?
Make some payments and refunds. Go to http://localhost:8099/applications/<application id>/payment-history/. Verify that the statement looks good.

Expected statement:
<img width="915" alt="Screen Shot 2020-09-02 at 11 36 16 AM" src="https://user-images.githubusercontent.com/1934992/92010100-5f78bb80-ed17-11ea-9b2f-36f73509dc30.png">

2020-09-04 16:36 UTC, mbertrand requested changes
Functionality works great

2020-09-04 16:36 UTC, mbertrand commented on static/js/pages/applications/PaymentHistoryPage_test.js
> +
Can you add a test checking that the correct label is on the page if there is a refund?

2020-09-08 22:02 UTC, abeglova commented
Thanks! Back to you

2020-09-09 13:11 UTC, mbertrand approved these changes
👍

2020-09-09 15:46 UTC, merged